USE FTPLATFORM;
select * into CORE_KLADROBJ_BCK30062025 from CORE_KLADROBJ;
delete from CORE_KLADROBJ;

INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(1 AS Numeric(19, 0)), N'0100000000000', N'Hà Nội', N'Tinh', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(2 AS Numeric(19, 0)), N'0100100000000', N'Ba Đình', N'Quan', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(3 AS Numeric(19, 0)), N'0100200000000', N'Phúc Xá', N'Quan', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(4 AS Numeric(19, 0)), N'0100100010000', N'Ba Đình', N'Phuong', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(5 AS Numeric(19, 0)), N'0100200020000', N'Ba Đình', N'Phuong', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(6 AS Numeric(19, 0)), N'0100100110000', N'Ba Đình', N'Phuong', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(7 AS Numeric(19, 0)), N'0200000000000', N'Test Tỉnh', N'Tinh', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(8 AS Numeric(19, 0)), N'0200100000000', N'Test Phường 1', N'Quan', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(9 AS Numeric(19, 0)), N'0200200000000', N'Test Phường 2', N'Quan', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(10 AS Numeric(19, 0)), N'0200300000000', N'Test Phường 3', N'Quan', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(11 AS Numeric(19, 0)), N'0200400000000', N'Test Xã 1', N'Huyen', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(12 AS Numeric(19, 0)), N'0200500000000', N'Test Xã 2', N'Huyen', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(13 AS Numeric(19, 0)), N'0200600000000', N'Test Đặc Khu 1', N'Thi Xa', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(14 AS Numeric(19, 0)), N'0200700000000', N'Test Đặc Khu 2', N'Thi Xa', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO
INSERT [dbo].[CORE_KLADROBJ] ([KLADROBJID], [CODE], [FULLNAME], [SHORTNAME], [POSTALCODE], [GNICODE], [UNO], [OKATO], [STATUS], [CODECUSTOM], [UPPERFULLNAME], [UPPERSHORTNAME]) VALUES (CAST(9284 AS Numeric(19, 0)), N'7900000000000', N'Hồ Chí Minh', N'Tinh', N'', N'0000', N'0000', N'', N'0', NULL, NULL, NULL)
GO